language: node_js
node_js:
  - 16
cache: yarn
install:
  - yarn
script:
  - CI=false && yarn build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: build
  on:
    branch: main  
